FROM node:alpine

ENV NODE_ENV=production
ENV PORT=5000


# TODO: add the Docker commands to do these steps:

# at build time:
# set the current directory to `/src`
# copy the manifest file: package.json into this directory
# from a shell, run `npm install`
# copy the content into place
# let traffic flow in on port 5000

# as the container starts:
# `npm start`
