apiVersion: v1
kind: Service
metadata:
  name: hellonode-service
spec:
  type: LoadBalancer # Docker Desktop forwards `LoadBalancer` to the KinD cluster
  selector:
    app: hellonode
  ports:
  - port: 3000
    targetPort: 3000
